name: Auto Tag and Release Version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  tag_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get current version from style.css
        id: get_version
        run: |
          VERSION=$(grep -i 'Version' style.css | awk '{print $2}')
          echo "Current theme version is $VERSION"
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Clean up Git state
        run: |
          git reset --hard
          git clean -fdx

      - name: Create new Git tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          if git tag -l | grep -q "$VERSION"; then
            echo "Tag $VERSION already exists. Skipping tagging."
          else
            git tag -a "$VERSION" -m "Release $VERSION"
            git push origin "$VERSION"
          fi

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          release_name: "Release ${{ env.version }}"
          body: "Automatically generated release for version ${{ env.version }}"
          draft: false
          prerelease: false
